/**
 * Durable contract for events generated by Cribl APM scheduled searches.
 *
 * Events are written back to the dataset with `| export tee=true to search
 * "<dataset>"`, which preserves the projected `datatype` field as-is (and
 * leaves `data_datatype` unset). Older rows — written by the previous,
 * now-unsupported `| send group="search"` path — landed with the outbound
 * `datatype` renamed to `data_datatype` (and the search-time `datatype`
 * classified as "Uncategorized"). Readers must therefore coalesce the two:
 * STORED_DATATYPE_EXPR bridges both the send→export migration and any rows
 * written before schema v1, for the supported upgrade window.
 */

export const GENERATED_EVENT_SCHEMA_VERSION = 1;
export const ALERT_EVENT_DATATYPE = 'criblapm_alert';
export const DEPLOY_EVENT_DATATYPE = 'criblapm_deploy';

/** Datatype expression that reads both export rows (`datatype`) and legacy
 * send rows (`data_datatype`). */
export const STORED_DATATYPE_EXPR =
  'coalesce(tostring(data_datatype), tostring(datatype))';

export interface GeneratedEventBase {
  schema_version: number;
  event_id: string;
  producer: string;
  is_canary?: boolean;
}

export interface AlertEvaluationEvent extends GeneratedEventBase {
  datatype: typeof ALERT_EVENT_DATATYPE;
  record_kind: 'evaluation';
  evaluation_id: string;
  evaluated_at: string | number;
  event_type: 'evaluated' | 'firing' | 'resolved';
  alert_id: string;
  alert_status: 'ok' | 'pending' | 'firing' | 'resolving';
  svc: string;
  signal_type: string;
  consecutive_bad: number;
  consecutive_good: number;
  fire_count: number;
}

export interface DeployEvent extends GeneratedEventBase {
  datatype: typeof DEPLOY_EVENT_DATATYPE;
  record_kind: 'deploy';
  svc: string;
  version: string;
  first_seen: number;
  n_spans: number;
}

export function generatedDatatypePredicate(datatype: string): string {
  if (datatype !== ALERT_EVENT_DATATYPE && datatype !== DEPLOY_EVENT_DATATYPE) {
    throw new Error(`unsupported generated-event datatype: ${datatype}`);
  }
  return `${STORED_DATATYPE_EXPR} == "${datatype}"`;
}

/**
 * Stable logical ID for legacy rows that predate event_id.  New producers
 * always populate event_id; this expression only prevents duplicate legacy
 * transition rows from being counted more than once by readers.
 */
export function eventIdExpr(fallbackFields: string[]): string {
  const pieces = fallbackFields.map((field) => `tostring(${field})`).join(', ":", ');
  return `coalesce(tostring(event_id), strcat("legacy:", ${pieces}))`;
}

function safeCanaryId(canaryId: string): string {
  if (!/^[a-zA-Z0-9_-]{1,96}$/.test(canaryId)) {
    throw new Error('canary ID must contain only letters, digits, underscores, and dashes');
  }
  return canaryId;
}

/** Emit one sentinel of each generated-event shape through the real send boundary. */
export function generatedEventContractCanarySend(canaryId: string, dataset: string): string {
  const id = safeCanaryId(canaryId);
  if (!/^[a-zA-Z0-9_-]+$/.test(dataset)) throw new Error('unsafe canary dataset');
  return `print datatype="${ALERT_EVENT_DATATYPE}",
               schema_version=tolong(${GENERATED_EVENT_SCHEMA_VERSION}),
               event_id="${id}:alert", producer="criblapm_contract_canary",
               record_kind="evaluation", evaluation_id="${id}",
               evaluated_at=now(), event_type="evaluated",
               alert_id="__canary__", alert_status="ok", svc="__canary__",
               signal_type="canary", consecutive_bad=tolong(0),
               consecutive_good=tolong(0), fire_count=tolong(0),
               dataset="${dataset}", is_canary=true
    | union (
        print datatype="${DEPLOY_EVENT_DATATYPE}",
              schema_version=tolong(${GENERATED_EVENT_SCHEMA_VERSION}),
              event_id="${id}:deploy", producer="criblapm_contract_canary",
              record_kind="deploy", svc="__canary__", version="${id}",
              first_seen=now(), n_spans=tolong(0), dataset="${dataset}",
              is_canary=true
      )
    | export tee=true to search "${dataset}"`;
}

/** Read the canaries through the same stored-field predicate used by consumers. */
export function generatedEventContractCanaryRead(canaryId: string, dataset: string): string {
  const id = safeCanaryId(canaryId);
  if (!/^[a-zA-Z0-9_-]+$/.test(dataset)) throw new Error('unsafe canary dataset');
  return `dataset="${dataset}"
    | where event_id in ("${id}:alert", "${id}:deploy")
    | where ${STORED_DATATYPE_EXPR} in ("${ALERT_EVENT_DATATYPE}", "${DEPLOY_EVENT_DATATYPE}")
    | summarize rows=count(),
                types=dcount(${STORED_DATATYPE_EXPR}),
                versions=dcount(tolong(schema_version)),
                canaries=countif(tostring(is_canary)=="true")`;
}
