/**
 * Durable contract for events generated by Cribl APM scheduled searches.
 *
 * The generic storage contract — write with `| export tee=true to search`,
 * read the datatype through both `datatype` and the legacy `send` path's
 * `data_datatype` (STORED_DATATYPE_EXPR), dedupe on a stable event id, and
 * prove the round trip with a canary — is the framework's
 * `@criblio/app-utils/generated-events`. This module binds APM's datatypes
 * and schema version into it ({@link GENERATED_EVENTS}) and owns what is
 * APM's: the event interfaces and the investigation/incident commit-query
 * builders.
 */
import {
  STORED_DATATYPE_EXPR,
  defineGeneratedEvents,
  eventIdExpr,
  kqlExpr,
} from '@criblio/app-utils/generated-events';

export { STORED_DATATYPE_EXPR, eventIdExpr };

export const GENERATED_EVENT_SCHEMA_VERSION = 1;
export const ALERT_EVENT_DATATYPE = 'criblapm_alert';
export const DEPLOY_EVENT_DATATYPE = 'criblapm_deploy';

/**
 * APM's generated events: the reader predicate and the post-reconcile
 * canary (send one sentinel per datatype through the real export boundary,
 * read it back through the consumers' predicate). Canary rows carry every
 * column of a real evaluation / deploy row ({@link AlertEvaluationEvent},
 * {@link DeployEvent}) — including the per-run `evaluation_id` / `version`
 * (the canary id) and the `now()`-typed `evaluated_at` / `first_seen` the
 * real producers write — so the round trip exercises the full shape through
 * the export boundary, as APM's own canary did before the framework uptake.
 * Every APM reader of these datatypes excludes them (`is_canary`, or an
 * event_type the canary never has).
 */
export const GENERATED_EVENTS = defineGeneratedEvents({
  datatypes: [ALERT_EVENT_DATATYPE, DEPLOY_EVENT_DATATYPE],
  schemaVersion: GENERATED_EVENT_SCHEMA_VERSION,
  canaryProducer: 'criblapm_contract_canary',
  canaryFields: {
    [ALERT_EVENT_DATATYPE]: (canaryId) => ({
      record_kind: 'evaluation', evaluation_id: canaryId, evaluated_at: kqlExpr('now()'),
      event_type: 'evaluated',
      alert_id: '__canary__', alert_status: 'ok', svc: '__canary__',
      signal_type: 'canary', consecutive_bad: 0, consecutive_good: 0, fire_count: 0,
    }),
    [DEPLOY_EVENT_DATATYPE]: (canaryId) => ({
      record_kind: 'deploy', svc: '__canary__', version: canaryId,
      first_seen: kqlExpr('now()'), n_spans: 0,
    }),
  },
});

/** Stored-datatype predicate for one APM generated-event datatype. */
export function generatedDatatypePredicate(
  datatype: typeof ALERT_EVENT_DATATYPE | typeof DEPLOY_EVENT_DATATYPE,
): string {
  return GENERATED_EVENTS.predicate(datatype);
}

export interface GeneratedEventBase {
  schema_version: number;
  event_id: string;
  producer: string;
  is_canary?: boolean;
}

export interface AlertEvaluationEvent extends GeneratedEventBase {
  datatype: typeof ALERT_EVENT_DATATYPE;
  record_kind: 'evaluation';
  evaluation_id: string;
  evaluated_at: string | number;
  event_type: 'evaluated' | 'firing' | 'resolved';
  alert_id: string;
  alert_status: 'ok' | 'pending' | 'firing' | 'resolving';
  svc: string;
  signal_type: string;
  consecutive_bad: number;
  consecutive_good: number;
  fire_count: number;
}

export interface DeployEvent extends GeneratedEventBase {
  datatype: typeof DEPLOY_EVENT_DATATYPE;
  record_kind: 'deploy';
  svc: string;
  version: string;
  first_seen: number;
  n_spans: number;
}

/**
 * Server-side investigation lifecycle, committed by the investigator
 * cell (producer `criblapm_cell_investigator`) through the same
 * `| export tee=true to search` boundary as evaluations. Uses
 * `record_kind: 'investigation'` and event_types disjoint from the
 * evaluation set, so every existing reader (state join, history,
 * noise budget) is blind to these rows by construction.
 */
export const INVESTIGATION_PRODUCER = 'criblapm_cell_investigator';

export type InvestigationEventType =
  | 'started'
  | 'investigated'
  | 'investigation_failed';

export interface InvestigationEvent extends GeneratedEventBase {
  datatype: typeof ALERT_EVENT_DATATYPE;
  record_kind: 'investigation';
  event_type: InvestigationEventType;
  alert_id: string;
  investigation_id: string;
  /** event_id of the firing evaluation row that triggered this run. */
  trigger_event_id: string;
  svc: string;
  signal_type: string;
  /** ≤1KB summary snippet; only on `investigated`. */
  conclusion?: string;
}

/** Max stored conclusion length — a snippet for the Alerts page, not
 *  the transcript (that lives in the cell, keyed by investigation_id). */
export const INVESTIGATION_CONCLUSION_MAX = 1024;

function kqlStr(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

/**
 * KQL that commits one investigation lifecycle event. Shared by the
 * cell (which runs it as a search job) and the contract canary, so
 * the write shape can't drift from the interface above.
 */
export function investigationEventCommitQuery(
  ev: Omit<InvestigationEvent, 'datatype' | 'record_kind' | 'schema_version' | 'producer'>,
  dataset: string,
): string {
  for (const [field, value] of Object.entries({
    event_id: ev.event_id,
    alert_id: ev.alert_id,
    investigation_id: ev.investigation_id,
    trigger_event_id: ev.trigger_event_id,
  })) {
    if (!value || typeof value !== 'string') {
      throw new Error(`investigation event ${field} must be a non-empty string`);
    }
  }
  const conclusion = (ev.conclusion ?? '').slice(0, INVESTIGATION_CONCLUSION_MAX);
  const canary = ev.is_canary ? `, is_canary=true` : '';
  return `print datatype="${ALERT_EVENT_DATATYPE}",
      schema_version=tolong(${GENERATED_EVENT_SCHEMA_VERSION}),
      event_id=${kqlStr(ev.event_id)},
      producer="${INVESTIGATION_PRODUCER}",
      record_kind="investigation",
      event_type=${kqlStr(ev.event_type)},
      alert_id=${kqlStr(ev.alert_id)},
      investigation_id=${kqlStr(ev.investigation_id)},
      trigger_event_id=${kqlStr(ev.trigger_event_id)},
      svc=${kqlStr(ev.svc)},
      signal_type=${kqlStr(ev.signal_type)},
      conclusion=${kqlStr(conclusion)}${canary}
    | export tee=true to search ${kqlStr(dataset)}`;
}

/**
 * Incident lifecycle — a warroom record above investigations (P4.4).
 * Written through the same `| export tee=true to search` boundary by the
 * app (human actions: notes, status, severity, close/reopen) and the
 * grouping search (opened / attached / resolved). `record_kind: 'incident'`
 * with event_types disjoint from every other set, so existing readers are
 * blind to these rows by construction. These events are the append-only
 * log; current state is materialized into the `criblapm_incidents` lookup.
 *
 * Design: docs/research/server-investigations/incidents-and-lifecycle.md.
 */
export const INCIDENT_GROUPER_PRODUCER = 'criblapm_incident_grouper';
export const INCIDENT_APP_PRODUCER = 'criblapm_app_incidents';

export type IncidentStatus =
  | 'open'
  | 'investigating'
  | 'identified'
  | 'mitigated'
  | 'resolved'
  | 'closed';

export type IncidentSeverity = 'sev1' | 'sev2' | 'sev3' | 'sev4';

export type IncidentEventType =
  | 'opened'
  | 'attached'
  | 'status_change'
  | 'severity_change'
  | 'note'
  | 'investigation_linked'
  | 'resolved'
  | 'closed';

export interface IncidentEvent extends GeneratedEventBase {
  datatype: typeof ALERT_EVENT_DATATYPE;
  record_kind: 'incident';
  event_type: IncidentEventType;
  incident_id: string;
  /** Who produced the event — drives the timeline's author tag. */
  author: 'agent' | 'human' | 'system';
  /** Incident status after this event (opened/attached/status_change/resolved/closed). */
  status?: IncidentStatus;
  severity?: IncidentSeverity;
  /** Root/primary service; the downstream-most erroring node. */
  root_service?: string;
  /** Comma-separated affected services (opened/attached). */
  services?: string;
  /** Markdown note body (on `note`); capped at INCIDENT_NOTE_MAX. */
  note?: string;
  /** Linked investigation (on `investigation_linked`). */
  investigation_id?: string;
  /** Alert evaluation event_id rolled in (on `attached`). */
  alert_event_id?: string;
  title?: string;
}

/** Max stored note length — the warroom timeline body. */
export const INCIDENT_NOTE_MAX = 4096;

/**
 * KQL that commits one incident lifecycle event. Shared by the app (human
 * actions) and the grouping search, so the write shape can't drift from
 * the interface above. `producer` distinguishes grouper vs app writes.
 */
export function incidentEventCommitQuery(
  ev: Omit<IncidentEvent, 'datatype' | 'record_kind' | 'schema_version'>,
  dataset: string,
): string {
  for (const [field, value] of Object.entries({
    event_id: ev.event_id,
    producer: ev.producer,
    incident_id: ev.incident_id,
    event_type: ev.event_type,
    author: ev.author,
  })) {
    if (!value || typeof value !== 'string') {
      throw new Error(`incident event ${field} must be a non-empty string`);
    }
  }
  const note = (ev.note ?? '').slice(0, INCIDENT_NOTE_MAX);
  const canary = ev.is_canary ? `, is_canary=true` : '';
  return `print datatype="${ALERT_EVENT_DATATYPE}",
      schema_version=tolong(${GENERATED_EVENT_SCHEMA_VERSION}),
      event_id=${kqlStr(ev.event_id)},
      producer=${kqlStr(ev.producer)},
      record_kind="incident",
      event_type=${kqlStr(ev.event_type)},
      incident_id=${kqlStr(ev.incident_id)},
      author=${kqlStr(ev.author)},
      status=${kqlStr(ev.status ?? '')},
      severity=${kqlStr(ev.severity ?? '')},
      root_service=${kqlStr(ev.root_service ?? '')},
      services=${kqlStr(ev.services ?? '')},
      note=${kqlStr(note)},
      investigation_id=${kqlStr(ev.investigation_id ?? '')},
      alert_event_id=${kqlStr(ev.alert_event_id ?? '')},
      title=${kqlStr(ev.title ?? '')}${canary}
    | export tee=true to search ${kqlStr(dataset)}`;
}
