/**
 * Durable contract for events generated by Cribl APM scheduled searches.
 *
 * Events are written back to the dataset with `| export tee=true to search
 * "<dataset>"`, which preserves the projected `datatype` field as-is (and
 * leaves `data_datatype` unset). Older rows — written by the previous,
 * now-unsupported `| send group="search"` path — landed with the outbound
 * `datatype` renamed to `data_datatype` (and the search-time `datatype`
 * classified as "Uncategorized"). Readers must therefore coalesce the two:
 * STORED_DATATYPE_EXPR bridges both the send→export migration and any rows
 * written before schema v1, for the supported upgrade window.
 */

export const GENERATED_EVENT_SCHEMA_VERSION = 1;
export const ALERT_EVENT_DATATYPE = 'criblapm_alert';
export const DEPLOY_EVENT_DATATYPE = 'criblapm_deploy';

/** Datatype expression that reads both export rows (`datatype`) and legacy
 * send rows (`data_datatype`). */
export const STORED_DATATYPE_EXPR =
  'coalesce(tostring(data_datatype), tostring(datatype))';

export interface GeneratedEventBase {
  schema_version: number;
  event_id: string;
  producer: string;
  is_canary?: boolean;
}

export interface AlertEvaluationEvent extends GeneratedEventBase {
  datatype: typeof ALERT_EVENT_DATATYPE;
  record_kind: 'evaluation';
  evaluation_id: string;
  evaluated_at: string | number;
  event_type: 'evaluated' | 'firing' | 'resolved';
  alert_id: string;
  alert_status: 'ok' | 'pending' | 'firing' | 'resolving';
  svc: string;
  signal_type: string;
  consecutive_bad: number;
  consecutive_good: number;
  fire_count: number;
}

export interface DeployEvent extends GeneratedEventBase {
  datatype: typeof DEPLOY_EVENT_DATATYPE;
  record_kind: 'deploy';
  svc: string;
  version: string;
  first_seen: number;
  n_spans: number;
}

/**
 * Server-side investigation lifecycle, committed by the investigator
 * cell (producer `criblapm_cell_investigator`) through the same
 * `| export tee=true to search` boundary as evaluations. Uses
 * `record_kind: 'investigation'` and event_types disjoint from the
 * evaluation set, so every existing reader (state join, history,
 * noise budget) is blind to these rows by construction.
 */
export const INVESTIGATION_PRODUCER = 'criblapm_cell_investigator';

export type InvestigationEventType =
  | 'started'
  | 'investigated'
  | 'investigation_failed';

export interface InvestigationEvent extends GeneratedEventBase {
  datatype: typeof ALERT_EVENT_DATATYPE;
  record_kind: 'investigation';
  event_type: InvestigationEventType;
  alert_id: string;
  investigation_id: string;
  /** event_id of the firing evaluation row that triggered this run. */
  trigger_event_id: string;
  svc: string;
  signal_type: string;
  /** ≤1KB summary snippet; only on `investigated`. */
  conclusion?: string;
}

/** Max stored conclusion length — a snippet for the Alerts page, not
 *  the transcript (that lives in the cell, keyed by investigation_id). */
export const INVESTIGATION_CONCLUSION_MAX = 1024;

function kqlStr(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

/**
 * KQL that commits one investigation lifecycle event. Shared by the
 * cell (which runs it as a search job) and the contract canary, so
 * the write shape can't drift from the interface above.
 */
export function investigationEventCommitQuery(
  ev: Omit<InvestigationEvent, 'datatype' | 'record_kind' | 'schema_version' | 'producer'>,
  dataset: string,
): string {
  for (const [field, value] of Object.entries({
    event_id: ev.event_id,
    alert_id: ev.alert_id,
    investigation_id: ev.investigation_id,
    trigger_event_id: ev.trigger_event_id,
  })) {
    if (!value || typeof value !== 'string') {
      throw new Error(`investigation event ${field} must be a non-empty string`);
    }
  }
  const conclusion = (ev.conclusion ?? '').slice(0, INVESTIGATION_CONCLUSION_MAX);
  const canary = ev.is_canary ? `, is_canary=true` : '';
  return `print datatype="${ALERT_EVENT_DATATYPE}",
      schema_version=tolong(${GENERATED_EVENT_SCHEMA_VERSION}),
      event_id=${kqlStr(ev.event_id)},
      producer="${INVESTIGATION_PRODUCER}",
      record_kind="investigation",
      event_type=${kqlStr(ev.event_type)},
      alert_id=${kqlStr(ev.alert_id)},
      investigation_id=${kqlStr(ev.investigation_id)},
      trigger_event_id=${kqlStr(ev.trigger_event_id)},
      svc=${kqlStr(ev.svc)},
      signal_type=${kqlStr(ev.signal_type)},
      conclusion=${kqlStr(conclusion)}${canary}
    | export tee=true to search ${kqlStr(dataset)}`;
}

/**
 * Incident lifecycle — a warroom record above investigations (P4.4).
 * Written through the same `| export tee=true to search` boundary by the
 * app (human actions: notes, status, severity, close/reopen) and the
 * grouping search (opened / attached / resolved). `record_kind: 'incident'`
 * with event_types disjoint from every other set, so existing readers are
 * blind to these rows by construction. These events are the append-only
 * log; current state is materialized into the `criblapm_incidents` lookup.
 *
 * Design: docs/research/server-investigations/incidents-and-lifecycle.md.
 */
export const INCIDENT_GROUPER_PRODUCER = 'criblapm_incident_grouper';
export const INCIDENT_APP_PRODUCER = 'criblapm_app_incidents';

export type IncidentStatus =
  | 'open'
  | 'investigating'
  | 'identified'
  | 'mitigated'
  | 'resolved'
  | 'closed';

export type IncidentSeverity = 'sev1' | 'sev2' | 'sev3' | 'sev4';

export type IncidentEventType =
  | 'opened'
  | 'attached'
  | 'status_change'
  | 'severity_change'
  | 'note'
  | 'investigation_linked'
  | 'resolved'
  | 'closed';

export interface IncidentEvent extends GeneratedEventBase {
  datatype: typeof ALERT_EVENT_DATATYPE;
  record_kind: 'incident';
  event_type: IncidentEventType;
  incident_id: string;
  /** Who produced the event — drives the timeline's author tag. */
  author: 'agent' | 'human' | 'system';
  /** Incident status after this event (opened/attached/status_change/resolved/closed). */
  status?: IncidentStatus;
  severity?: IncidentSeverity;
  /** Root/primary service; the downstream-most erroring node. */
  root_service?: string;
  /** Comma-separated affected services (opened/attached). */
  services?: string;
  /** Markdown note body (on `note`); capped at INCIDENT_NOTE_MAX. */
  note?: string;
  /** Linked investigation (on `investigation_linked`). */
  investigation_id?: string;
  /** Alert evaluation event_id rolled in (on `attached`). */
  alert_event_id?: string;
  title?: string;
}

/** Max stored note length — the warroom timeline body. */
export const INCIDENT_NOTE_MAX = 4096;

/**
 * KQL that commits one incident lifecycle event. Shared by the app (human
 * actions) and the grouping search, so the write shape can't drift from
 * the interface above. `producer` distinguishes grouper vs app writes.
 */
export function incidentEventCommitQuery(
  ev: Omit<IncidentEvent, 'datatype' | 'record_kind' | 'schema_version'>,
  dataset: string,
): string {
  for (const [field, value] of Object.entries({
    event_id: ev.event_id,
    producer: ev.producer,
    incident_id: ev.incident_id,
    event_type: ev.event_type,
    author: ev.author,
  })) {
    if (!value || typeof value !== 'string') {
      throw new Error(`incident event ${field} must be a non-empty string`);
    }
  }
  const note = (ev.note ?? '').slice(0, INCIDENT_NOTE_MAX);
  const canary = ev.is_canary ? `, is_canary=true` : '';
  return `print datatype="${ALERT_EVENT_DATATYPE}",
      schema_version=tolong(${GENERATED_EVENT_SCHEMA_VERSION}),
      event_id=${kqlStr(ev.event_id)},
      producer=${kqlStr(ev.producer)},
      record_kind="incident",
      event_type=${kqlStr(ev.event_type)},
      incident_id=${kqlStr(ev.incident_id)},
      author=${kqlStr(ev.author)},
      status=${kqlStr(ev.status ?? '')},
      severity=${kqlStr(ev.severity ?? '')},
      root_service=${kqlStr(ev.root_service ?? '')},
      services=${kqlStr(ev.services ?? '')},
      note=${kqlStr(note)},
      investigation_id=${kqlStr(ev.investigation_id ?? '')},
      alert_event_id=${kqlStr(ev.alert_event_id ?? '')},
      title=${kqlStr(ev.title ?? '')}${canary}
    | export tee=true to search ${kqlStr(dataset)}`;
}

export function generatedDatatypePredicate(datatype: string): string {
  if (datatype !== ALERT_EVENT_DATATYPE && datatype !== DEPLOY_EVENT_DATATYPE) {
    throw new Error(`unsupported generated-event datatype: ${datatype}`);
  }
  return `${STORED_DATATYPE_EXPR} == "${datatype}"`;
}

/**
 * Stable logical ID for legacy rows that predate event_id.  New producers
 * always populate event_id; this expression only prevents duplicate legacy
 * transition rows from being counted more than once by readers.
 */
export function eventIdExpr(fallbackFields: string[]): string {
  const pieces = fallbackFields.map((field) => `tostring(${field})`).join(', ":", ');
  return `coalesce(tostring(event_id), strcat("legacy:", ${pieces}))`;
}

function safeCanaryId(canaryId: string): string {
  if (!/^[a-zA-Z0-9_-]{1,96}$/.test(canaryId)) {
    throw new Error('canary ID must contain only letters, digits, underscores, and dashes');
  }
  return canaryId;
}

/** Emit one sentinel of each generated-event shape through the real send boundary. */
export function generatedEventContractCanarySend(canaryId: string, dataset: string): string {
  const id = safeCanaryId(canaryId);
  if (!/^[a-zA-Z0-9_-]+$/.test(dataset)) throw new Error('unsafe canary dataset');
  return `print datatype="${ALERT_EVENT_DATATYPE}",
               schema_version=tolong(${GENERATED_EVENT_SCHEMA_VERSION}),
               event_id="${id}:alert", producer="criblapm_contract_canary",
               record_kind="evaluation", evaluation_id="${id}",
               evaluated_at=now(), event_type="evaluated",
               alert_id="__canary__", alert_status="ok", svc="__canary__",
               signal_type="canary", consecutive_bad=tolong(0),
               consecutive_good=tolong(0), fire_count=tolong(0),
               dataset="${dataset}", is_canary=true
    | union (
        print datatype="${DEPLOY_EVENT_DATATYPE}",
              schema_version=tolong(${GENERATED_EVENT_SCHEMA_VERSION}),
              event_id="${id}:deploy", producer="criblapm_contract_canary",
              record_kind="deploy", svc="__canary__", version="${id}",
              first_seen=now(), n_spans=tolong(0), dataset="${dataset}",
              is_canary=true
      )
    | export tee=true to search "${dataset}"`;
}

/** Read the canaries through the same stored-field predicate used by consumers. */
export function generatedEventContractCanaryRead(canaryId: string, dataset: string): string {
  const id = safeCanaryId(canaryId);
  if (!/^[a-zA-Z0-9_-]+$/.test(dataset)) throw new Error('unsafe canary dataset');
  return `dataset="${dataset}"
    | where event_id in ("${id}:alert", "${id}:deploy")
    | where ${STORED_DATATYPE_EXPR} in ("${ALERT_EVENT_DATATYPE}", "${DEPLOY_EVENT_DATATYPE}")
    | summarize rows=count(),
                types=dcount(${STORED_DATATYPE_EXPR}),
                versions=dcount(tolong(schema_version)),
                canaries=countif(tostring(is_canary)=="true")`;
}
